---
###############################################################################
#                   MUST keep all parameter names the same                    #
###############################################################################
model_params:
  lrf: 0.985
  batch_size: 1
  epochs: 80
  levels: 5
  seg_levels: 3
  test_size: 0.3
  shuffle: False
  standardize: True
  verbose: 1
  model_checkpoint_dir: "scratch/model-checkpoints"
lightcone_shape: !!python/tuple [256, 128, 128]
lightcone_dimensions: !!python/tuple [512, 256, 256]
