---
model_params:
  lrf: 0.985
  batch_size: 2
  epochs: 80
  levels: 5
  seg_levels: 3
  test_size: 0.5
  shuffle: False # DO NOT CHANGE - dataset is already shuffled.
  standardize: True
  verbose: 1
cube_shape: !!python/tuple [128, 128, 128]
cube_dimensions: !!python/tuple [128, 128, 128]
